name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - name: install and test plugin
        run: ./scripts/test.bash
